# Generated by Django 4.2.6 on 2023-11-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/bannerAdds')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(max_length=40)),
            ],
        ),
    ]
