# Generated by Django 4.2.6 on 2023-11-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletter_name_alter_newsletter_surname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='title',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='message',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
